### PR TITLE
Leverage JSON source generation.

### LINKED ISSUE #52: Support JsonSerializerContext source generation for System.Text.Json
https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/

### PR DESCRIPTION
**Pull request by ejball**
Fixes #52.

### CODE REVIEW

**Comment by ejball** [comment]
Waiting for .NET 8 bug fix.

**Comment by ejball** [comment]
I had hoped to enable it by default, but it slightly increases assembly size and slightly decreases performance. It may be worth considering for its [other benefits](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/reflection-vs-source-generation). I am open to being persuaded that it should be the default.

`Facility.ConformanceApi.dll` grows from 147 KB to 151 KB.

Compare `SystemTextJson` (reflection) to `BenchmarkServiceJson`:
```
| Method   | UserCount | Serializer           | Mean       | Error    | StdDev   | Median     | Gen0     | Gen1     | Allocated  |
|--------- |---------- |--------------------- |-----------:|---------:|---------:|-----------:|---------:|---------:|-----------:|
| GetUsers | 1         | BenchmarkServiceJson | 1,121.0 us |  6.70 us | 18.80 us | 1,117.0 us |  62.5000 |  19.5313 |  823.91 KB |
| GetUsers | 1         | MessagePack          |   585.1 us |  3.39 us |  9.84 us |   585.3 us |  35.1563 |  11.7188 |  462.94 KB |
| GetUsers | 1         | NewtonsoftJson       | 1,878.5 us | 10.95 us | 32.10 us | 1,873.5 us | 367.1875 | 128.9063 |  4722.9 KB |
| GetUsers | 1         | SystemTextJson       | 1,080.2 us |  4.14 us | 11.95 us | 1,077.8 us |  62.5000 |  23.4375 |  826.95 KB |
| GetUsers | 10        | BenchmarkServiceJson | 1,124.3 us |  6.64 us | 18.93 us | 1,123.3 us |  62.5000 |  19.5313 |  829.72 KB |
| GetUsers | 10        | MessagePack          |   583.8 us |  3.54 us | 10.23 us |   583.3 us |  35.1563 |   9.7656 |   465.1 KB |
| GetUsers | 10        | NewtonsoftJson       | 1,922.4 us | 12.04 us | 35.11 us | 1,916.6 us | 367.1875 | 125.0000 | 4729.16 KB |
| GetUsers | 10        | SystemTextJson       | 1,086.6 us |  4.81 us | 13.73 us | 1,083.8 us |  62.5000 |  19.5313 |  829.47 KB |
| GetUsers | 100       | BenchmarkServiceJson | 1,167.3 us |  9.03 us | 26.33 us | 1,161.4 us |  66.4063 |  23.4375 |   859.2 KB |
| GetUsers | 100       | MessagePack          |   603.8 us |  4.74 us | 13.75 us |   604.2 us |  39.0625 |  13.6719 |  499.56 KB |
| GetUsers | 100       | NewtonsoftJson       | 1,984.6 us | 13.22 us | 38.14 us | 1,980.5 us | 371.0938 | 125.0000 | 4771.13 KB |
| GetUsers | 100       | SystemTextJson       | 1,139.8 us |  5.40 us | 15.74 us | 1,140.4 us |  66.4063 |  23.4375 |  861.13 KB |
| GetUsers | 1000      | BenchmarkServiceJson | 1,777.5 us | 22.08 us | 64.41 us | 1,760.2 us |  85.9375 |  31.2500 | 1169.69 KB |
| GetUsers | 1000      | MessagePack          |   967.4 us |  6.08 us | 17.45 us |   966.6 us |  62.5000 |  19.5313 |   809.2 KB |
| GetUsers | 1000      | NewtonsoftJson       | 2,767.9 us | 29.31 us | 85.97 us | 2,769.4 us | 402.3438 | 167.9688 | 5142.14 KB |
| GetUsers | 1000      | SystemTextJson       | 1,678.9 us | 14.64 us | 42.69 us | 1,676.6 us |  89.8438 |  31.2500 | 1169.61 KB |
```

**Comment by ddunkin** [comment]
It seems like the kind of thing each consumer might want to control. I wonder about putting it behind a build-time flag other than `NET8_0_OR_GREATER`. For example, only build it for the iOS target.

**Comment by ejball** [comment]
Something like `--json-source-gen-condition "IOS || ANDROID"`?

**Comment by ejball** [comment]
@ddunkin Added `--json-source-gen-if`.

**Pull request merged**
