### PR TITLE
Fix null value in Enum.IsDefined()

### PR DESCRIPTION
**Pull request by jvannoord**

### CODE REVIEW

**Comment by ejball** [comment]
Sorry, I really need to add a "Contributing" page.

For the build to succeed, you'll need to run `build.ps1 codegen` and push those changes.

If you could add a test to `EnumTests`, that would be outstanding.

To publish a new version, change `Directory.Build.props`, add a heading to `ReleaseNotes.md`, and it will automatically publish when merged to `master`.

**Comment by jvannoord** [comment]
My version changes got lost somewhere, not sure where/how. I don't have easy access to a windows machine at the moment, so the powershell stuff will have to happen another time. Justin will likely submit all the things.

**Comment by ejball** [comment]
FWIW, it should work fine with PowerShell on [macOS or Linux](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7.1#powershell).

**Comment by jvannoord** [comment]
TIL

**Pull request closed without merging**
